const data = {
  products: [
    {
      name: 'Product #1',
      slug: 'product1',
      category: 'Skincare',
      image: '/images/mockup.png',
      price: 20,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Amazing Product',
    },
    {
      name: 'Product #2',
      slug: 'product2',
      category: 'Skincare',
      image: '/images/mockup.png',
      price: 21,
      rating: 4.5,
      numReviews: 9,
      countInStock: 19,
      description: 'Amazing Product',
    },
    {
      name: 'Product #3',
      slug: 'product3',
      category: 'Skincare',
      image: '/images/mockup.png',
      price: 22,
      rating: 4.5,
      numReviews: 8,
      countInStock: 18,
      description: 'Amazing Product',
    },
    {
      name: 'Product #4',
      slug: 'product4',
      category: 'Skincare',
      image: '/images/mockup.png',
      price: 23,
      rating: 4.5,
      numReviews: 7,
      countInStock: 17,
      description: 'Amazing Product',
    },
    {
      name: 'Product #5',
      slug: 'product5',
      category: 'Skincare',
      image: '/images/mockup.png',
      price: 24,
      rating: 4.5,
      numReviews: 6,
      countInStock: 16,
      description: 'Amazing Product',
    },
    {
      name: 'Product #6',
      slug: 'product6',
      category: 'Haircare',
      image: '/images/mockup.png',
      price: 25,
      rating: 4.5,
      numReviews: 5,
      countInStock: 15,
      description: 'Amazing Product',
    },
    {
      name: 'Product #7',
      slug: 'product7',
      category: 'Haircare',
      image: '/images/mockup.png',
      price: 26,
      rating: 4.5,
      numReviews: 6,
      countInStock: 14,
      description: 'Amazing Product',
    },
    {
      name: 'Product #8',
      slug: 'product8',
      category: 'Haircare',
      image: '/images/mockup.png',
      price: 27,
      rating: 4.5,
      numReviews: 5,
      countInStock: 13,
      description: 'Amazing Product',
    },
    {
      name: 'Product #9',
      slug: 'product9',
      category: 'Haircare',
      image: '/images/mockup.png',
      price: 28,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Amazing Product',
    },
  ],
};
export default data;